version: '3.7'

services:
  db:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend_network
  
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: DOCKERFILE
    env_file:
      - ./backend/couscous.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/backend
      - static-volume:/usr/src/backend/static
    networks:
      - backend_network
    command: >
     sh -c "python manage.py collectstatic --noinput &&
              python manage.py makemigrations --noinput &&
              python manage.py migrate --noinput &&
              gunicorn couscous.wsgi:application -w 2 -b :8000 --reload"

volumes:
  static-volume:
  pgdata:

networks:
  backend_network:
