# Generated by Django 2.2.7 on 2019-11-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OP', 'Open'), ('PA', 'Paid'), ('OV', 'Overdue'), ('CA', 'Canceled')], max_length=2, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_invoice', to='debtor.Debtor')),
            ],
        ),
    ]
